version: '3'

services:
  #nginx:
    #image: nginx:1.14
    #container_name: nginx
    #volumes:
      #- ./code/:/var/www/code
      #- ./logs/:/var/log/nginx
      #- ./nginx/conf/conf.d/:/etc/nginx/conf.d
      #- ./nginx/conf/ssl/:/etc/nginx/ssl
    #ports:
      #- "80:80"
      #- "443:443"

  gome:
    build:
      context: ./golang
    container_name: gome
    volumes:
      - ./code/:/go/src
      - ./code/gome:/go/src/gome
      - ./supervisor:/etc/supervisor/conf.d
    ports:
      - "8088:8088"
    tty: true

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
      - ./rabbitmq/etc/:/etc/rabbitmq/
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./logs/:/var/log/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: "username"
      RABBITMQ_DEFAULT_PASS: "password"
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:5.0
    container_name: redis
    ports:
      - "6379:6379"

  #database:
    #build:
      #context: ./database
    #environment:
      #- MYSQL_DATABASE=mydb
      #- MYSQL_USER=myuser
      #- MYSQL_PASSWORD=secret
      #- MYSQL_ROOT_PASSWORD=docker
      #- TZ=Asia/Shanghai
